#!/usr/bin/env bun
/**
 * editio-doctor.ts — workspace health, report-only. The scaffold generates a
 * workspace once and the plugin keeps moving; nothing else can tell when the two
 * drift apart (the second dogfood found a live paper on a pre-0.3.0 main.tex with
 * none of the venue float discipline — and no way to know). The doctor names the
 * drift; fixing it stays the author's move (usually `editio-scaffold --force`,
 * which never touches authored files).
 *
 * Usage:
 *   editio-doctor.ts [--root <dir>] [--strict]
 *
 * Checks (each a named line, ok or FLAG):
 *   order      main.tex's wired sections vs the DECLARED order (paper.json × the
 *              project's own doco-deo.json) — regeneration follows the declared
 *              order, so this drift makes --force rewire the paper (proven by a
 *              dry-run on a real drifted workspace: 4 core sections dropped)
 *   stamp      main.tex's scaffold version vs the installed plugin's (the --force
 *              advice is withheld while the order is drifted)
 *   venue      packages/preamble the venue data ships that main.tex lacks
 *   sty        workspace editio.sty vs the plugin's (older scaffold or local edits)
 *   metadata   a hand-finished front/metadata.tex (no GENERATED header) that
 *              --force would clobber
 *   render     sections/*.md newer than their .tex (or never rendered)
 *   wiring     sections/*.md that main.tex never inputs (silently unbuilt prose)
 *   fences     plain ```latex fences carrying \cite/\ref/\cref (the latex+ fence
 *              renders those; plain fences stay byte-raw by contract)
 *   identity   paper.json author names appearing in section prose (identity lives
 *              in front/metadata.tex only, where blind mode can mask it)
 *
 * Report-only by design: every fix is judgment or an existing command. `--strict`
 * exits 1 when anything is flagged (CI / pre-submission gating); a missing
 * workspace exits 2 either way.
 */
import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { findRoot, paperDir, readJSON } from "./lib.ts";

const PLUGIN = join(dirname(fileURLToPath(import.meta.url)), "..");
const TEMPLATES = join(PLUGIN, "templates");

function arg(argv: string[], k: string): string | undefined {
  const i = argv.indexOf(`--${k}`);
  return i >= 0 && argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[i + 1] : undefined;
}

export interface Finding { check: string; detail: string }

const norm = (s: string) => s.replace(/\r\n/g, "\n");

/** The plugin's own version — the reference every stamp is compared against. */
export function pluginVersion(): string {
  return String(readJSON(join(PLUGIN, ".claude-plugin", "plugin.json")).version);
}

/** Parse the scaffold stamp out of a generated main.tex; null on pre-stamp scaffolds. */
export function scaffoldStamp(mainTex: string): string | null {
  return mainTex.match(/GENERATED by editio-scaffold v(\d+\.\d+\.\d+)/)?.[1] ?? null;
}

const semverLt = (a: string, b: string) => {
  const pa = a.split(".").map(Number);
  const pb = b.split(".").map(Number);
  for (let i = 0; i < 3; i++) if (pa[i] !== pb[i]) return pa[i] < pb[i];
  return false;
};

export function diagnose(root: string): { findings: Finding[]; notes: string[] } {
  const paper = paperDir(root);
  const findings: Finding[] = [];
  const notes: string[] = [];
  const flag = (check: string, detail: string) => findings.push({ check, detail });

  const meta = readJSON(join(paper, "paper.json"));
  const metaVenue = String(meta.venue ?? "arxiv");

  const mainTexPath = join(paper, "main.tex");
  const mainTex = existsSync(mainTexPath) ? norm(readFileSync(mainTexPath, "utf8")) : null;
  if (!mainTex) flag("stamp", "no main.tex — run editio-scaffold");

  // the venue main.tex was actually generated for governs the drift checks below;
  // paper.json disagreeing with it is its own drift (a --venue run leaves paper.json alone)
  const generatedVenue = mainTex?.match(/for venue "([\w-]+)"/)?.[1] ?? null;
  if (generatedVenue && generatedVenue !== metaVenue) {
    flag("venue", `main.tex was generated for venue "${generatedVenue}" but paper.json names "${metaVenue}" — align paper.json, or rescaffold with --force`);
  }
  const venueId = generatedVenue ?? metaVenue;
  const venuePath = join(TEMPLATES, "venues", venueId, "venue.json");
  const venue = existsSync(venuePath) ? readJSON(venuePath) : null;
  if (!venue) flag("venue", `venue "${venueId}" has no venue data in the plugin`);

  // order drift — the declared order (paper.json × the project's OWN structure-gate
  // copy) vs what main.tex actually wires. A paper legitimately evolves past its
  // declared order by hand-editing generated main.tex; regeneration follows the
  // DECLARED order, so until it's reconciled, --force rewires the paper (the dry-run
  // on a real drifted workspace dropped 4 core sections and seeded 3 stubs).
  let orderDrift = false;
  const gatePath = join(root, ".editio", "schema", "doco-deo.json");
  if (mainTex && existsSync(gatePath)) {
    const gate = readJSON(gatePath);
    const orderId = String(meta.order ?? "");
    const order: string[] | undefined = gate.orders?.[orderId];
    if (!order) {
      orderDrift = true;
      flag("order", `paper.json declares order "${orderId}" but .editio/schema/doco-deo.json has no such order — add it (the gate copy is project-tunable) or fix paper.json`);
    } else {
      const declared = order.filter((c) => c !== "doco:BibliographicReferenceList")
        .map((c) => String(gate.section_slugs?.[c] ?? c.split(":").pop()!.toLowerCase()));
      const wired = [...mainTex.matchAll(/InputIfFileExists\{sections\/([\w-]+)\}/g)].map((m) => m[1]);
      if (declared.join(" ") !== wired.join(" ")) {
        orderDrift = true;
        flag("order", `main.tex wires [${wired.join(", ")}] but the declared order "${orderId}" expands to [${declared.join(", ")}] — the paper outgrew its declared order; reconcile it (a custom order in .editio/schema/doco-deo.json + paper.json) BEFORE any --force, which follows the declared order and would rewire the paper`);
      }
    }
  }

  // stamp — which scaffold generated this workspace?
  const current = pluginVersion();
  const forceAdvice = orderDrift
    ? "— but do NOT --force yet: the declared order is stale (see the order flag); reconcile it first"
    : "— editio-scaffold --force regenerates it (authored files survive)";
  if (mainTex) {
    const stamp = scaffoldStamp(mainTex);
    if (!stamp) flag("stamp", `main.tex carries no scaffold version stamp (a pre-${current} scaffold) ${forceAdvice}`);
    else if (semverLt(stamp, current)) flag("stamp", `main.tex was generated by editio-scaffold v${stamp}; the plugin is v${current} ${forceAdvice}`);
    else notes.push(`stamp: scaffold v${stamp}`);
  }

  // venue drift — what the venue data ships that the generated preamble lacks.
  // front/macros.tex counts: a hand-carried fix there is present, just authored.
  if (mainTex && venue) {
    const macrosPath = join(paper, "front", "macros.tex");
    const preambleText = mainTex + (existsSync(macrosPath) ? norm(readFileSync(macrosPath, "utf8")) : "");
    for (const p of venue.packages ?? []) {
      const name = String(p).replace(/^\[[^\]]*\]/, "").replace(/[{}]/g, "");
      if (!new RegExp(`\\\\usepackage(\\[[^\\]]*\\])?\\{${name}\\}`).test(preambleText)) {
        flag("venue", `venue "${venueId}" ships \\usepackage{${name}} but neither main.tex nor front/macros.tex has it`);
      }
    }
    for (const line of venue.preamble ?? []) {
      const l = String(line).trim();
      if (!l || l.startsWith("%")) continue;
      // a hand-tuned value is not drift: \renewcommand{\x}/\setcounter{x} match by name
      const key = l.match(/^\\(?:renewcommand\{\\[\w@]+\}|setcounter\{[\w@]+\})/)?.[0] ?? l;
      if (!preambleText.includes(key)) flag("venue", `venue preamble line missing from main.tex/macros.tex: ${l}`);
    }
  }

  // sty — the render layer is generated verbatim; any difference is drift.
  const styPath = join(paper, "editio.sty");
  if (!existsSync(styPath)) flag("sty", "no editio.sty — run editio-scaffold");
  else if (norm(readFileSync(styPath, "utf8")) !== norm(readFileSync(join(TEMPLATES, "latex", "editio.sty"), "utf8"))) {
    flag("sty", "editio.sty differs from the plugin's (older scaffold, or local edits that --force would overwrite — move keepers to front/macros.tex first)");
  }

  // metadata — front/metadata.tex is generated, but a real paper hand-finished it
  // (the compsoc author block the generator can't express) and left a "do NOT
  // --force" comment inside a generated file. Detect the hand-finish by its
  // missing GENERATED header and say what regeneration would cost.
  const metaTexPath = join(paper, "front", "metadata.tex");
  if (existsSync(metaTexPath) && !norm(readFileSync(metaTexPath, "utf8")).includes("GENERATED from paper.json")) {
    flag("metadata", "front/metadata.tex is hand-finished (no GENERATED header) — editio-scaffold --force would clobber it; keep it aside and re-apply, and upstream whatever paper.json could not express");
  }

  // render + wiring + fences + identity — per section
  const sectionsDir = join(paper, "sections");
  const slugs = existsSync(sectionsDir)
    ? readdirSync(sectionsDir).filter((f) => f.endsWith(".md")).map((f) => f.replace(/\.md$/, "")).sort()
    : [];
  const authors: string[] = Array.isArray(meta.authors) ? meta.authors.map((a: any) => String(a?.name ?? "")).filter(Boolean) : [];
  let stale = 0;
  for (const slug of slugs) {
    const mdPath = join(sectionsDir, `${slug}.md`);
    const texPath = join(sectionsDir, `${slug}.tex`);
    if (!existsSync(texPath)) { flag("render", `sections/${slug}.md was never rendered`); }
    else if (statSync(mdPath).mtimeMs > statSync(texPath).mtimeMs) stale++;

    if (mainTex && !mainTex.includes(`sections/${slug}`)) {
      flag("wiring", `sections/${slug}.md exists but main.tex never inputs it — the prose silently doesn't build`);
    }

    const md = norm(readFileSync(mdPath, "utf8"));
    for (const m of md.matchAll(/```latex\n([\s\S]*?)```/g)) {
      if (/\\(cite|ref|cref|Cref)\b/.test(m[1])) {
        const line = md.slice(0, m.index!).split("\n").length;
        flag("fences", `sections/${slug}.md:${line} — a plain \`\`\`latex fence hand-writes \\cite/\\ref; the \`\`\`latex+ fence renders [@key]/@fig: instead`);
      }
    }
    md.split("\n").forEach((raw, i) => {
      for (const name of authors) {
        if (raw.includes(name)) flag("identity", `sections/${slug}.md:${i + 1} names author "${name}" in prose — identity belongs in front/metadata.tex, where blind mode masks it`);
      }
    });
  }
  if (stale) flag("render", `${stale} section(s) have .md newer than .tex — run editio-render --all`);
  notes.push(`sections: ${slugs.length}`);

  return { findings, notes };
}

function main(argv: string[]): number {
  const root = arg(argv, "root") ?? findRoot(process.cwd());
  const paper = paperDir(root);
  if (!existsSync(join(paper, "paper.json"))) {
    console.error(`editio-doctor: no ${join(paper, "paper.json")} — not an editio workspace (searched upward from the cwd); pass --root <dir>`);
    return 2;
  }
  const { findings, notes } = diagnose(root);
  console.log(`editio-doctor: ${paper} (plugin v${pluginVersion()}${notes.length ? ` · ${notes.join(" · ")}` : ""})`);
  if (!findings.length) {
    console.log("  healthy — scaffold current, renders fresh, sections wired, prose identity-clean.");
    return 0;
  }
  for (const f of findings) console.log(`  FLAG ${f.check.padEnd(8)} ${f.detail}`);
  const forceUnsafe = findings.some((f) => f.check === "order" || f.check === "metadata");
  console.log(`  ${findings.length} finding(s) — report-only; ${forceUnsafe
    ? "reconcile the order/metadata flags first — only then are editio-scaffold --force and editio-render --all the usual fixes."
    : "the usual fixes are editio-scaffold --force (generated files) and editio-render --all."}`);
  return argv.includes("--strict") ? 1 : 0;
}

if (import.meta.main) process.exit(main(process.argv.slice(2)));
