/** Read canonical Promptus identity/lifecycle directly; no cache or installed-plugin discovery.
 * vendor/promptus is generated by sync-reader.ts from the canonical source, never hand-edited. */
import { existsSync } from "node:fs";
import { join } from "node:path";
import { collectEffectiveUnits } from "./vendor/promptus/read-store.ts";
import { loadVocab, type Vocab } from "./vendor/promptus/vocab.ts";
import defaults from "./vendor/promptus/default-vocab.json";
import { slugify } from "./lib.ts";

export interface GroundUnit { substrate: string; status: string; id?: string; path: string; title: string }

export function storeUnits(root: string): Map<string, GroundUnit> {
  // Legacy minimal stores remain readable without creating vocabulary or caches.
  const vocab = existsSync(join(root, ".promptus/schema/kb-vocab.json")) ? loadVocab(root) : structuredClone(defaults) as Vocab;
  // Archive location changes retrieval scope, not epistemic status. Manuscript
  // grounds are explicit identities and must survive ordinary source archiving.
  const units = collectEffectiveUnits(root, vocab);

  const map = new Map<string, GroundUnit>();
  const ambiguous = new Set<string>();
  const add = (key: string | null | undefined, unit: typeof units[number]) => {
    if (!key || ambiguous.has(key)) return;
    const current = map.get(key);
    if (current && (current.path !== unit.relPath || current.title !== unit.title)) {
      map.delete(key); ambiguous.add(key); return;
    }
    map.set(key, { substrate: unit.substrate, status: unit.status, id: unit.id, path: unit.relPath, title: unit.title });
  };
  // Preserve the canonical precedence of IDs/slugs over compatibility aliases.
  for (const unit of units) { add(unit.id, unit); add(unit.slug, unit); }
  const direct = new Set([...map.keys(), ...ambiguous]);
  for (const unit of units) {
    for (const alias of unit.aliases) if (!direct.has(alias)) add(alias, unit);
    // Earlier Editio versions addressed ledger entries by their untruncated title slug.
    if (unit.substrate === "ledger" && !direct.has(slugify(unit.title))) add(slugify(unit.title), unit);
  }
  return map;
}
