/**
 * doctor.test.ts — editio-doctor's contract: a fresh scaffold is healthy; every
 * drift class the second dogfood surfaced (pre-stamp main.tex, missing venue
 * discipline, stale sty/renders, unwired sections, hand-cite fences, identity in
 * prose) is flagged by name; --strict turns findings into exit 1; report-only
 * otherwise. Runs the real scripts through the bun binary against temp roots.
 */
import { test, expect, afterAll } from "bun:test";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, utimesSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const DOCTOR = join(import.meta.dir, "..", "editio-doctor.ts");
const SCAFFOLD = join(import.meta.dir, "..", "editio-scaffold.ts");
const RENDER = join(import.meta.dir, "..", "editio-render.ts");
const VERSION = JSON.parse(readFileSync(join(import.meta.dir, "..", "..", ".claude-plugin", "plugin.json"), "utf8")).version;

const tmps: string[] = [];
afterAll(() => { for (const d of tmps) { try { rmSync(d, { recursive: true, force: true }); } catch { /* ignore */ } } });

function scratch(): string {
  const d = mkdtempSync(join(tmpdir(), "editio-doctor-test-"));
  tmps.push(d);
  return d;
}
function run(script: string, root: string, ...args: string[]) {
  const r = spawnSync(process.execPath, [script, "--root", root, ...args], { encoding: "utf8" });
  return { status: r.status ?? -1, out: `${r.stdout ?? ""}${r.stderr ?? ""}` };
}
const paper = (root: string, ...p: string[]) => join(root, ".editio", "paper", ...p);
const read = (p: string) => readFileSync(p, "utf8");

/** A scaffolded + fully rendered workspace — the healthy baseline. */
function healthy(venue = "arxiv"): string {
  const root = scratch();
  expect(run(SCAFFOLD, root, "--venue", venue).status).toBe(0);
  expect(run(RENDER, root, "--all").status).toBe(0);
  return root;
}

test("a fresh scaffold + render is healthy, and the stamp names the plugin version", () => {
  const root = healthy();
  const r = run(DOCTOR, root);
  expect(r.status).toBe(0);
  expect(r.out).toContain("healthy");
  expect(r.out).toContain(`scaffold v${VERSION}`);
  expect(read(paper(root, "main.tex"))).toContain(`GENERATED by editio-scaffold v${VERSION}`);
});

test("a pre-stamp main.tex (the Psi case) is flagged, and --strict exits 1", () => {
  const root = healthy();
  const main = paper(root, "main.tex");
  writeFileSync(main, read(main).replace(/GENERATED by editio-scaffold v[\d.]+/, "GENERATED by editio-scaffold"));
  const r = run(DOCTOR, root);
  expect(r.status).toBe(0); // report-only by default
  expect(r.out).toContain("FLAG stamp");
  expect(r.out).toContain("no scaffold version stamp");
  expect(run(DOCTOR, root, "--strict").status).toBe(1);
});

test("an older stamp is flagged with both versions named", () => {
  const root = healthy();
  const main = paper(root, "main.tex");
  writeFileSync(main, read(main).replace(/editio-scaffold v[\d.]+/, "editio-scaffold v0.1.0"));
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG stamp");
  expect(r.out).toContain("v0.1.0");
  expect(r.out).toContain(`v${VERSION}`);
});

test("a --venue run that outpaced paper.json is flagged as venue drift", () => {
  const root = healthy(); // scaffolds arxiv; paper.json says arxiv
  expect(run(SCAFFOLD, root, "--venue", "tpami", "--force").status).toBe(0); // main.tex now tpami, paper.json untouched
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG venue");
  expect(r.out).toContain('generated for venue "tpami"');
  expect(r.out).toContain('"arxiv"');
});

test("venue drift: tpami discipline stripped from main.tex is flagged; hand-carrying it in macros.tex clears the flag", () => {
  const root = healthy("tpami");
  const meta = paper(root, "paper.json");
  writeFileSync(meta, read(meta).replace('"venue": "arxiv"', '"venue": "tpami"'));
  const main = paper(root, "main.tex");
  writeFileSync(main, read(main)
    .replace("\\usepackage{dblfloatfix}\n", "")
    .replace("\\renewcommand{\\dbltopfraction}{0.9}\n", ""));
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG venue");
  expect(r.out).toContain("dblfloatfix");
  expect(r.out).toContain("\\dbltopfraction");

  // the first dogfood's actual fix — the same discipline hand-carried in front/macros.tex,
  // even at a tuned value (0.92, the Psi variant) — is not drift
  writeFileSync(paper(root, "front", "macros.tex"),
    "\\usepackage{dblfloatfix}\n\\renewcommand{\\dbltopfraction}{0.92}\n");
  const r2 = run(DOCTOR, root);
  expect(r2.out).not.toContain("FLAG venue");
});

test("a locally edited editio.sty is flagged as drift", () => {
  const root = healthy();
  const sty = paper(root, "editio.sty");
  writeFileSync(sty, read(sty) + "\n% local tweak\n");
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG sty");
  expect(r.out).toContain("front/macros.tex");
});

test("stale and never-rendered sections are flagged", () => {
  const root = healthy();
  const intro = paper(root, "sections", "introduction.md");
  const future = new Date(Date.now() + 60_000);
  utimesSync(intro, future, future); // md newer than its tex
  rmSync(paper(root, "sections", "conclusion.tex"));
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG render");
  expect(r.out).toContain("newer than .tex");
  expect(r.out).toContain("conclusion.md was never rendered");
});

test("a section main.tex never inputs is flagged as unwired", () => {
  const root = healthy();
  writeFileSync(paper(root, "sections", "appendix-extra.md"), "---\nclass: deo:Discussion\nstatus: drafting\ngrounds: []\n---\n# Extra\n");
  run(RENDER, root, "--all");
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG wiring");
  expect(r.out).toContain("appendix-extra.md");
});

test("hand-written cites in a plain latex fence get the latex+ nudge, with file:line", () => {
  const root = healthy();
  const intro = paper(root, "sections", "introduction.md");
  writeFileSync(intro, read(intro) + "\n```latex\n\\begin{table}\\caption{Per \\cite{key}}\\end{table}\n```\n");
  run(RENDER, root, "--all");
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG fences");
  expect(r.out).toMatch(/introduction\.md:\d+/);
  expect(r.out).toContain("latex+");
});

test("an author name from paper.json appearing in prose is flagged at file:line", () => {
  const root = healthy();
  const meta = paper(root, "paper.json");
  writeFileSync(meta, read(meta).replace("Author One", "Grace Hopper"));
  const intro = paper(root, "sections", "introduction.md");
  writeFileSync(intro, read(intro) + "\nAs Grace Hopper showed earlier.\n");
  run(RENDER, root, "--all");
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG identity");
  expect(r.out).toContain("Grace Hopper");
  expect(r.out).toMatch(/introduction\.md:\d+/);
});

test("outside any workspace the doctor exits 2 with an honest error", () => {
  const bare = scratch();
  const r = run(DOCTOR, bare);
  expect(r.status).toBe(2);
  expect(r.out).toContain("not an editio workspace");
});

test("cwd-proof: run from inside .editio/paper without --root", () => {
  const root = healthy();
  const r = spawnSync(process.execPath, [DOCTOR], { cwd: paper(root), encoding: "utf8" });
  expect(r.status).toBe(0);
  expect(`${r.stdout}`).toContain("healthy");
});

// ──────────── hardening: the Psi dry-run (a --force that would rewire the paper) ────────────

test("order drift: main.tex outgrowing the declared order is flagged, and the stamp advice withholds --force", () => {
  const root = healthy(); // template paper.json declares order cs-systems
  const main = paper(root, "main.tex");
  // the Psi shape: the paper evolved by hand-editing generated main.tex — a section
  // the declared order expands to is gone, so regeneration would rewire the build
  writeFileSync(main, read(main)
    .replace("\InputIfFileExists{sections/methods}{}{}\n", "")
    .replace(/GENERATED by editio-scaffold v[\d.]+/, "GENERATED by editio-scaffold")); // and it's pre-stamp
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG order");
  expect(r.out).toContain('declared order "cs-systems"');
  expect(r.out).toContain("would rewire the paper");
  expect(r.out).toContain("FLAG stamp");
  expect(r.out).toContain("do NOT --force yet"); // the advice is gated on the order being clean
  expect(r.out).not.toContain("authored files survive");
});

test("a declared order missing from the project gate copy is flagged", () => {
  const root = healthy();
  const meta = paper(root, "paper.json");
  writeFileSync(meta, read(meta).replace('"order": "cs-systems"', '"order": "my-bespoke-order"'));
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG order");
  expect(r.out).toContain('no such order');
});

test("a hand-finished front/metadata.tex (no GENERATED header) is flagged before --force can clobber it", () => {
  const root = healthy();
  writeFileSync(paper(root, "front", "metadata.tex"),
    "% hand-finished compsoc author block — do NOT --force without re-applying\n\title{X}\n\author{Y}\n");
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG metadata");
  expect(r.out).toContain("hand-finished");
});

// ──────────── strays: hand-saved PDFs in the paper source root (the Gauging-Ψ incident) ────────────

test("a stray PDF in the paper source root is flagged per file; PDFs under build/ are not", () => {
  const root = healthy();
  mkdirSync(paper(root, "build"), { recursive: true });
  writeFileSync(paper(root, "build", "main_pub.pdf"), "%PDF-1.5 current publish build");
  const clean = run(DOCTOR, root);
  expect(clean.out).not.toContain("FLAG strays"); // build/ is where PDFs belong

  // the incident shape: a bare default name plus an ad-hoc snapshot, both loose in the root
  writeFileSync(paper(root, "main.pdf"), "%PDF-1.5 three-versions-stale draft");
  writeFileSync(paper(root, "gauging-psi-v1.pdf"), "%PDF-1.5 hand-saved snapshot");
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG strays");
  expect(r.out).toContain("main.pdf sits in the paper source root");
  expect(r.out).toContain("gauging-psi-v1.pdf sits in the paper source root");
  expect(r.out).toContain("archive/");
  expect(run(DOCTOR, root, "--strict").status).toBe(1);
});

test("a stray that byte-duplicates a build/ output is called out as safe to delete", () => {
  const root = healthy();
  mkdirSync(paper(root, "build"), { recursive: true });
  writeFileSync(paper(root, "build", "main_pub.pdf"), "%PDF-1.5 identical bytes");
  writeFileSync(paper(root, "main.pdf"), "%PDF-1.5 identical bytes");
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG strays");
  expect(r.out).toContain("byte-for-byte copy of build/main_pub.pdf");
  expect(r.out).toContain("safe to delete");
});

// ──────────── vcs: the paper's history is git's job (the zero-versions incident) ────────────

const git = (root: string, ...a: string[]) => spawnSync("git", ["-C", root, ...a], { encoding: "utf8" });

test("paper sources in a git repo but never tracked are flagged; tracked sources clear it", () => {
  const root = healthy();
  expect(git(root, "init", "-q").status).toBe(0);
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG vcs");
  expect(r.out).toContain("never tracked");
  expect(run(DOCTOR, root, "--strict").status).toBe(1);

  git(root, "add", ".editio");
  const r2 = run(DOCTOR, root);
  expect(r2.out).not.toContain("FLAG vcs");
  expect(r2.out).toContain("vcs: sources tracked");
});

test("gitignored paper sources (the incident shape) are flagged with the un-ignore advice", () => {
  const root = healthy();
  expect(git(root, "init", "-q").status).toBe(0);
  writeFileSync(join(root, ".gitignore"), ".editio/\n");
  const r = run(DOCTOR, root);
  expect(r.out).toContain("FLAG vcs");
  expect(r.out).toContain("gitignored");
  expect(r.out).toContain("build*/ dirs ignored");
});

test("outside any git repo the doctor notes untracked history without flagging", () => {
  const root = healthy(); // scratch dirs live under the OS tmpdir, outside any repo
  const r = run(DOCTOR, root);
  expect(r.out).not.toContain("FLAG vcs");
  expect(r.out).toContain("vcs: no git repository");
});
