/**
 * numbers.test.ts — editio-numbers' contract: one source of truth per value.
 * The scenarios mirror the second dogfood's failure modes: a headline number
 * typed into many sentences (binding kills the copies), sources changing after
 * values were written (the lock catches what luck caught in the field), and a
 * deliberate freeze (pinned passes on the record). Runs the real script through
 * the bun binary against temp roots.
 */
import { test, expect, afterAll } from "bun:test";
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const NUMBERS = join(import.meta.dir, "..", "editio-numbers.ts");
const tmps: string[] = [];
afterAll(() => { for (const d of tmps) { try { rmSync(d, { recursive: true, force: true }); } catch { /* ignore */ } } });

/** A minimal workspace: sections + numbers.json + a fake results source. */
function scaffold(): string {
  const root = mkdtempSync(join(tmpdir(), "editio-numbers-test-"));
  tmps.push(root);
  const paper = join(root, ".editio", "paper");
  mkdirSync(join(paper, "sections"), { recursive: true });
  mkdirSync(join(paper, "front"), { recursive: true });
  mkdirSync(join(root, "results"), { recursive: true });
  writeFileSync(join(root, "results", "baseline.json"), JSON.stringify({ mean_ari: 0.872 }));
  writeFileSync(join(paper, "sections", "evaluation.md"), [
    "---",
    "class: deo:Evaluation",
    "---",
    "# Experiments",
    "",
    "The mean is @num:mean-ari in prose and $@num:mean-ari$ in math.",
    "",
    "```latex+",
    "\\caption{mean @num:mean-ari}",
    "```",
    "",
  ].join("\n"));
  writeFileSync(join(paper, "numbers.json"), JSON.stringify({
    "mean-ari": { value: "0.872", source: "results/baseline.json", computed_by: "scripts/bench.py" },
    "volcano-ari": "0.622",
  }, null, 2));
  return root;
}

function run(root: string, ...args: string[]) {
  const r = spawnSync(process.execPath, [NUMBERS, "--root", root, ...args], { encoding: "utf8" });
  return { status: r.status ?? -1, out: `${r.stdout ?? ""}${r.stderr ?? ""}` };
}
const paper = (root: string, ...p: string[]) => join(root, ".editio", "paper", ...p);

test("--write binds values into front/numbers.tex (csname defs) and locks source hashes", () => {
  const root = scaffold();
  const r = run(root, "--write");
  expect(r.status).toBe(0);
  const tex = readFileSync(paper(root, "front", "numbers.tex"), "utf8");
  expect(tex).toContain("GENERATED by editio-numbers");
  expect(tex).toContain("\\expandafter\\gdef\\csname editionum@mean-ari\\endcsname{0.872}");
  expect(tex).toContain("\\csname editionum@volcano-ari\\endcsname{0.622}");
  const lock = JSON.parse(readFileSync(paper(root, "front", "numbers.lock.json"), "utf8"));
  expect(Object.keys(lock.sources)).toEqual(["results/baseline.json"]);
});

test("the report names usage, freshness, and unused handles; the gate passes clean", () => {
  const root = scaffold();
  run(root, "--write");
  const r = run(root, "--gate");
  expect(r.status).toBe(0);
  expect(r.out).toContain("used ×3"); // prose + math + latex+ caption
  expect(r.out).toContain("fresh");
  expect(r.out).toMatch(/volcano-ari.*unused/);
  expect(r.out).toContain("numbers-clean");
});

test("a changed source flips the handle to STALE and fails the gate — pinning passes on the record", () => {
  const root = scaffold();
  run(root, "--write");
  writeFileSync(join(root, "results", "baseline.json"), JSON.stringify({ mean_ari: 0.874 })); // the field's exact failure
  const r = run(root, "--gate");
  expect(r.status).toBe(1);
  expect(r.out).toContain("STALE");
  expect(r.out).toContain("results/baseline.json changed since --write");
  expect(r.out).toContain("re-run scripts/bench.py"); // the remediation names the pipeline

  const nj = JSON.parse(readFileSync(paper(root, "numbers.json"), "utf8"));
  nj["mean-ari"].pinned = "frozen with the submission tag 2026-07-04";
  writeFileSync(paper(root, "numbers.json"), JSON.stringify(nj, null, 2));
  run(root, "--write");
  const r2 = run(root, "--gate");
  expect(r2.status).toBe(0);
  expect(r2.out).toContain("PINNED (frozen with the submission tag 2026-07-04)");
});

test("unknown handles and @num inside a byte-raw fence fail the gate at file:line", () => {
  const root = scaffold();
  run(root, "--write");
  writeFileSync(paper(root, "sections", "evaluation.md"), [
    "# Experiments",
    "",
    "Typo: @num:mean-arii here.",
    "",
    "```latex",
    "raw fence: @num:mean-ari never renders",
    "```",
    "",
  ].join("\n"));
  const r = run(root, "--gate");
  expect(r.status).toBe(1);
  expect(r.out).toContain("unknown handle @num:mean-arii at sections/evaluation.md:3");
  expect(r.out).toMatch(/byte-raw fence at sections\/evaluation\.md:\d+/);
  expect(r.out).toContain("latex+");
});

test("bindings referenced but never written, or older than numbers.json, fail the gate", () => {
  const root = scaffold();
  const r = run(root, "--gate"); // no --write yet
  expect(r.status).toBe(1);
  expect(r.out).toContain("front/numbers.tex missing");

  run(root, "--write");
  expect(run(root, "--gate").status).toBe(0);
  const later = new Date(Date.now() + 60_000);
  const nj = paper(root, "numbers.json");
  writeFileSync(nj, readFileSync(nj, "utf8")); // touch: json newer than tex
  const { utimesSync } = require("node:fs");
  utimesSync(nj, later, later);
  const r2 = run(root, "--gate");
  expect(r2.status).toBe(1);
  expect(r2.out).toContain("numbers.json is newer than front/numbers.tex");
});

test("values that never left the pipeline: no numbers.json is honest, not fatal", () => {
  const root = scaffold();
  rmSync(paper(root, "numbers.json"));
  writeFileSync(paper(root, "sections", "evaluation.md"), "# E\n\nNo bound numbers here.\n");
  const r = run(root, "--gate");
  expect(r.status).toBe(0);
  expect(r.out).toContain("0 handle(s)");
});

test("cwd-proof: run from inside .editio/paper without --root", () => {
  const root = scaffold();
  run(root, "--write");
  const r = spawnSync(process.execPath, [NUMBERS], { cwd: paper(root), encoding: "utf8" });
  expect(r.status).toBe(0);
  expect(`${r.stdout}`).toContain("2 handle(s)");
});
